### ISSUE TITLE
How do i run a Snap! save file in the subset.

### ISSUE THREAD

**Issue by JSJBDEV** [Rydion/SnapSubset#3]
Hello, sorry to bother you again;
i'm making a game which I would like to work on IOS and Android so, because snap is coded in java script i'm using snap. (because although phosphorus and scratch work there is absolutely no IO for game saving) so my simple question is; how do i execute an snap file through the subset, is there something i'm missing?

**Comment by adrian-hintze** [comment]
Hi, SnapSubset generates Subsets (reduced functionality) of Snap!, once they are done you use the resulting code as any other instance of Snap!. The only difference is that the subsets expect to find the following in the code of gui.js:

IDE_Morph.prototype.snapproject = 'XML string representing the project to load'; 

I don't know exactly what your use case is, but I'm guessing that you want to achieve something similar to what Snapp! does but on mobile. In that case I would recommend you to just get the reduced version of Snap! from there and insert your project into it as shown above. SnapSubset hasn't been updated for a while and although I still use it, it has become quite a pain in the ass to use due to ES6 and some bugs in the code (and I can't really promise that I will be able to correct any of them any time soon).

If what you want is to build your own SnapSubset just let me know and I'll help you with it.
